### ISSUE TITLE
Dataset Seems Incomplete?

### ISSUE THREAD

**Issue by yravan** [pereira-gha/activefire#12]
Hi, thank you for publishing the code & dataset. I downloaded the manual annotation dataset using the scripts provided. I get a folder called "landsat_patches" with 9045 images. However, the "manual_annotation_patches" folder only has 101 images and the "mask_patches" folder only has 1099. Should the latter two also have 9045, or is this correct?. Thanks!

**Comment by Minoro** [comment]
Hello,
We are glad about your interest in our project!
About the masks, in order to save space we only provide the masks (manual annotations) that have at least one fire pixel. The patches without any fire will have a black mask, therefore we didn't provide it as images. However, we provide a script to generate these masks on your machine, the script is: `scr/utils/generate_nonfire_masks.py`. 

The folder `src/utils` has some scripts that can help you use this repository. You can read more about it on the [main page](https://github.com/pereira-gha/activefire?tab=readme-ov-file#useful-stuff).

Please, let me know if the script helps you.

**Comment by Minoro** [comment]
I`m close this issue due to inactivity. If you still having issues, please fell free to open another one.
