### ISSUE TITLE
Problem with the donwloader.py in landsat

### ISSUE THREAD

**Issue by UrielMendoza** [pereira-gha/activefire#6]
Hello.
When i try to run the downloader.py, i get this error:

```
1 LC08_L1TP_118016_20200901_20200901_01_RT
http://landsat-pds.s3.amazonaws.com/c1/L8/118/016/LC08_L1TP_118016_20200901_20200901_01_RT/LC08_L1TP_118016_20200901_20200901_01_RT_BQA.TIF
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 260, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 215, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_HttpResponseError: HTTP response code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/urielm/activefire_fork/activefire/src/landsat/downloader.py", line 55, in <module>
    with rasterio.open(link) as src:
  File "/usr/lib/python3/dist-packages/rasterio/env.py", line 435, in wrapper
    return f(*args, **kwds)
  File "/usr/lib/python3/dist-packages/rasterio/__init__.py", line 207, in open
    s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio/_base.pyx", line 262, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: HTTP response code: 404
```

I think it is because of the access to the s3.amazonaws cube for landsat, do you have another option to download the landsat files?

**Comment by Minoro** [comment]
Hello,
I believe you can use the Google Earth Engine that provides the Landsat-8 images through Google Cloud Storage:

- https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_TOA
- https://cloud.google.com/storage/docs/public-datasets/landsat?hl=pt_br

If you are using a CSV as we did in our work you may need to change the URL format. This code can help you build the URL to download images from Google Cloud:


```python
import pandas as pd

def build_url(row):
    # The product ID is something like 'LC08_L1TP_118016_20200901_20200901_01_RT'
    parts = row['productId'].split('_')
    sensor_id = parts[0] # LC08
    product = parts[1] # L1TP
    path = parts[2][:3] # 118
    r = parts[2][3:] # 016

    # Adjust the URL 
    base_url = 'https://storage.googleapis.com/gcp-public-data-landsat/'
    url = base_url + sensor_id + '/01/' +  path + '/' + r + '/' + row['productId'] + '/' + row['productId']

    return url

df = pd.read_csv('dataset.csv', delimiter=';')
# Adjust the URL
df['gs_url'] = df.apply(build_url, axis=1)
```
This code will convert the Landsat product ID to a Google Storage URL, you can download the individual bands by adding the band suffix to the URL. Let's say you want the BQA band from Product `LC08_L1TP_118016_20200901_20200901_01_RT`, you need to add the `_BQA.TIF` suffix. The URL would be: `https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/118/016/LC08_L1TP_118016_20200901_20200901_01_RT/LC08_L1TP_118016_20200901_20200901_01_RT_BQA.TIF`

If you want  Band 1 the URL would be: `https://storage.googleapis.com/gcp-public-data-landsat/LC08/01/118/016/LC08_L1TP_118016_20200901_20200901_01_RT/LC08_L1TP_118016_20200901_20200901_01_RT_B1.TIF`

You can also navigate through the Landsat collection: `[gs://gcp-public-data-landsat](https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/?hl=pt-br&_ga=2.51672429.-553358645.1611142589)`

I didn't check if the images available in the Google Storage match with those used in our work (stored in the AWS), because the main goal of our work wasn't a tool to download images, and we already provide a (croped) dataset ready-to-use.  

I hope this helps you.

**Comment by UrielMendoza** [comment]
Hi thanks.

I changed the aws url to the suggested one and it worked fine for the month of February 2021.

I did the pull request if you want to add it.

Thank you very much for the reply.
